version: '3.3'
services:
  post_db:
    image: mongo:3.2
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db

  ui:
    image: ${IMGUSERNAME}/ui:${UI_VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    ports:
      - ${UI_PORT}
    networks:
      - front_net

  post:
    image: ${IMGUSERNAME}/post:${POST_VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    networks:
      back_net:
        aliases:
          - post
      front_net:
        aliases:
          - post

  comment:
    image: ${IMGUSERNAME}/comment:${COMMENT_VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      back_net:
        aliases:
          - comment
      front_net:
        aliases:
          - comment

volumes:
  post_db:

networks:
  back_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.2.0/24

  front_net: 
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.1.0/24
